baseURL = "https://til.kapilvarshney.com"
languageCode = "en-us"
title = "Kapil Varshney"
theme = "kiss"
pygmentsStyle = "monokai"
pygmentsCodefences = true
enableRobotsTXT = true


[params.info]
  homeTitle = "Kapil Varshney - Things I've Learned"
  enableSocial = true

[params.social]
  archive = "/posts/"
  github = "kapil-varshney"
  linkedin = "kapilvarshney14"
  profile = "https://medium.com/@kapilvarshney"
