baseURL = "https://til.zqureshi.in"
languageCode = "en-us"
title = "Zeeshan Qureshi"
theme = "kiss"
pygmentsStyle = "monokai"
pygmentsCodefences = true
enableRobotsTXT = true

[params.info]
  homeTitle = "Zeeshan Qureshi - Things I've Learned"
  enableSocial = true

[params.social]
  github = "zqureshi"
